### ISSUE TITLE
Replace Google Analytics +

### ISSUE THREAD

**Issue by brashrebel** [realbig/rbw-functionality#4]
This is a plugin which tracks network wide traffic. Not interested in that anymore. We need the tracking code to only be on realbigwebsites.com and nothing else.

**Comment by d4mation** [comment]
Do we have a Tracking Code for `realbigwebsites.com`? I don't seem to have access if we do.

**Comment by brashrebel** [comment]
Added you.

**Comment by d4mation** [comment]
Added the tracking code to the Footer on `realbigwebsites.com` and deactivated the plugin.
