### ISSUE TITLE
Broken Image on Login Screen

### ISSUE THREAD

**Issue by d4mation** [realbig/rbw-functionality#5]
The login screen's CSS tries to load `http://realbigmarketing.com/files/2013/04/Blue-Green-Logo.png` which is a 404. 

Do we have another copy of that laying around to point it to?

**Comment by brashrebel** [comment]
![blue-green-logo](https://cloud.githubusercontent.com/assets/4993131/13353436/659bc220-dc62-11e5-9f1d-ca913382ac6b.png)
